## Лабораторная работа 1.4

Реализовать метод вращений в виде программы, задавая в качестве входных
данных матрицу и точность вычислений. Используя разработанное программное обеспечение, найти собственные значения и собственные векторы симметрических матриц. Проанализировать зависимость погрешности вычислений от числа
итераций.

In [1]:
import numpy as np
import math 

def Jacobi(A, e):
    n = len(A)
    
    # Инициализация матриц вращения
    A = np.matrix(A)
    USt = np.matrix(np.eye(n))
    iter = 0
    while True:
        iter += 1
        
        # Вычисление максимального недиагональный элемента матрицы:
        mi, mj, mmax = 0, 0, 0
        for i in range(n):
            for j in range(i + 1, n):
                if mmax < abs(A[i, j]):
                    mmax = abs(A[i, j])
                    mi, mj = i, j
                    
        #print("максимальный элемент, строка, столбец", mmax, mi, mj)
        
        # Вычисление угла вращения
        if A[mi, mi] != A[mj, mj]:
            phi = math.atan(2 * A[mi, mj] / (A[mi, mi] - A[mj, mj])) / 2 
            #print('угол вращения:', phi)
        else:
            phi = pi / 4
            #print('угол вращения:', phi)
        
        # Вычисление матрицы вращения
        U = np.matrix(np.eye(n))
        U[mi, mi], U[mi, mj] = math.cos(phi), -math.sin(phi)
        U[mj, mi], U[mj, mj] = math.sin(phi),  math.cos(phi)
        #print('матрица вращения:', U)
        
        # Обновление матриц
        
        A = U.T * A * U
        
        t = 0
        
        for i in range(n):
            for j in range(i + 1, n):
                t += A[i, j] * A[i, j]
                
        if t < e**2: break
        
        USt = np.matmul(USt, U)
    return np.asarray(A.diagonal())[0], np.asarray(USt), iter


A = np.array([[-6, 6, -8],
              [6, -4, 9],
              [-8, 9, -2]])

eps = 0.01
znach, vect, iter = Jacobi(A, eps)
print('Количество итераций:', iter)
print('Собственные значения:')
print(znach)
print('Собственные векторы:')
print(vect)

Количество итераций: 6
Собственные значения:
[  0.77069675 -19.34414228   6.57344552]
Собственные векторы:
[[ 0.76141961 -0.59591222 -0.25520345]
 [ 0.62389902  0.56672685  0.53811773]
 [-0.17604029 -0.56895458  0.80330599]]
